config: config/nv3d.yaml
expname: nv3d
render_only: false
render_train: false
render_test: true
render_path: true
systems:
  seed: 20220401
  basedir: ./logs
  ckpt: null
  progress_refresh_rate: 10
  vis_every: 50000
  add_timestamp: true
model:
  model_name: Cplane
  N_voxel_init: 262144
  N_voxel_final: 27000000
  step_ratio: 0.5
  nonsquare_voxel: true
  time_grid_init: 31
  time_grid_final: 300
  normalize_type: normal
  upsample_list:
  - 70000
  - 14000000
  - 21000000
  update_emptymask_list:
  - 50000
  - 100000
  density_n_comp:
  - 12
  - 12
  - 12
  app_n_comp:
  - 24
  - 24
  - 24
  density_dim: 1
  app_dim: 27
  DensityMode: general_MLP
  AppMode: general_MLP
  init_scale: 0.1
  init_shift: 0.0
  fusion_one: multiply
  fusion_two: sum
  fea2denseAct: softplus
  density_shift: -10.0
  distance_scale: 25.0
  density_t_pe: -1
  density_pos_pe: -1
  density_view_pe: -1
  density_gen_latent: 3
  density_fea_pe: 2
  density_featureC: 128
  density_n_layers: 3
  app_t_pe: -1
  app_pos_pe: -1
  app_view_pe: 2
  app_gen_latent: 3
  app_fea_pe: 2
  app_featureC: 128
  app_n_layers: 3
  emptyMask_thes: 0.001
  rayMarch_weight_thres: 0.0001
  random_background: false
  depth_loss: false
  depth_loss_weight: 1.0
  dist_loss: false
  dist_loss_weight: 0.01
  TV_t_s_ratio: 2.0
  TV_weight_density: 0.0005
  TV_weight_app: 0.0005
  L1_weight_density: 0.0
  L1_weight_app: 0.0
  align_corners: true
  upsampling_type: aligned
  nSamples: 1000000
model_fine:
  model_name: Cplane
  N_voxel_init: 2097152
  N_voxel_final: 27000000
  step_ratio: 0.5
  nonsquare_voxel: true
  time_grid_init: 16
  time_grid_final: 20
  normalize_type: normal
  upsample_list:
  - 3000
  - 6000
  - 9000
  update_emptymask_list:
  - 4000
  - 8000
  - 10000
  density_n_comp:
  - 24
  - 24
  - 24
  app_n_comp:
  - 48
  - 48
  - 48
  density_dim: 1
  app_dim: 27
  DensityMode: general_MLP
  AppMode: general_MLP
  init_scale: 0.1
  init_shift: 0.0
  fusion_one: multiply
  fusion_two: sum
  fea2denseAct: softplus
  density_shift: -10.0
  distance_scale: 25.0
  density_t_pe: -1
  density_pos_pe: -1
  density_view_pe: -1
  density_gen_latent: 3
  density_fea_pe: 2
  density_featureC: 128
  density_n_layers: 3
  app_t_pe: -1
  app_pos_pe: -1
  app_view_pe: 2
  app_gen_latent: 3
  app_fea_pe: 2
  app_featureC: 128
  app_n_layers: 3
  emptyMask_thes: 0.001
  rayMarch_weight_thres: 0.0001
  random_background: false
  depth_loss: false
  depth_loss_weight: 1.0
  dist_loss: false
  dist_loss_weight: 0.01
  TV_t_s_ratio: 2.0
  TV_weight_density: 0.0001
  TV_weight_app: 0.0001
  L1_weight_density: 0.0
  L1_weight_app: 0.0
  align_corners: true
  upsampling_type: aligned
  nSamples: 1000000
data:
  datadir: ./Neural_3D_Video/flame_salmon_1
  dataset_name: neural3D_NDC
  downsample: 2.0
  cal_fine_bbox: false
  N_vis: 5
  time_scale: 1.0
  scene_bbox_min:
  - -2.5
  - -2.0
  - -1.0
  scene_bbox_max:
  - 2.5
  - 2.0
  - 1.0
  N_random_pose: 10
  nv3d_ndc_bd_factor: 0.75
  nv3d_ndc_eval_step: 1
  nv3d_ndc_eval_index: 0
  nv3d_ndc_sphere_scale: 1.0
  stage_1_iteration: 300
  stage_2_iteration: 2500
  stage_3_iteration: 9000
  key_f_num: 30
  stage_1_gamma: 0.001
  stage_2_gamma: 0.02
  stage_3_alpha: 0.1
  datasampler_type: images
optim:
  lr_density_grid: 0.02
  lr_app_grid: 0.02
  lr_density_nn: 0.001
  lr_app_nn: 0.001
  beta1: 0.9
  beta2: 0.99
  lr_decay_type: exp
  lr_decay_target_ratio: 0.1
  lr_decay_step: -1
  lr_upsample_reset: true
  batch_size: 2048
  n_iters: 400000
optim_fine:
  lr_density_grid: 0.0002
  lr_app_grid: 0.0002
  lr_density_nn: 0.0001
  lr_app_nn: 0.0001
  beta1: 0.009
  beta2: 0.0099
  lr_decay_type: exp
  lr_decay_target_ratio: 0.1
  lr_decay_step: -1
  lr_upsample_reset: false
  batch_size: 3000
  n_iters: 2000
