systems:
  basedir: "./logs"

model:
  model_name: "Cplane"
  N_voxel_init: 262144
  time_grid_init: 16
  time_grid_final: 50
  upsampling_type: unaligned
  upsample_list: [3000, 6000, 9000]
  update_emptymask_list: [4000, 8000, 10000]
  fusion_one: "multiply"
  fusion_two: "multiply"
  init_scale: 0.9
  init_shift: 0.5
  density_dim: 8
  DensityMode: "general_MLP"

model_fine:
  model_name: "Cplane_fine"
  N_voxel_init: 524288
  time_grid_init: 16
  time_grid_final: 24
  upsampling_type: unaligned
  upsample_list: [100, 200, 300]
  update_emptymask_list: [4000, 8000, 10000]
  fusion_one: "multiply"
  fusion_two: "multiply"
  init_scale: 0.9
  init_shift: 0.5
  density_dim: 8
  DensityMode: "general_MLP"
 


data:
  datadir: "./nerf/nerf_synthetic/nerf_synthetic/lego" #"./D-NeRF_ori/data/jumpingjacks" #"./nerf/nerf_synthetic/nerf_synthetic/lego"  #  "./D-NeRF_ori/data/jumpingjacks"#"./D-NeRF_ori/data/hook" # "./MonoNeRf/data/Balloon2" #"./MonoNeRf/data/Balloon2"
  dataset_name:  "dnerf"
  scene_bbox_min: [-1.5, -1.5, -1.5]
  scene_bbox_max: [1.5, 1.5, 1.5]
  downsample: 4.0

optim:
  n_iters: 30000
  lr_decay_type: "exp"

render_test: True
render_path: True
expname: dnerf