systems:
  basedir: "./logs"
  vis_every: 50000

model:
  N_voxel_init: 262144
  time_grid_init: 31
  time_grid_final: 300
  upsampling_type: aligned
  upsample_list: [70000, 14000000, 21000000]
  update_emptymask_list: [50000, 100000]
  fusion_one: "multiply"
  fusion_two: "sum"
  density_n_comp: [12, 12, 12]
  app_n_comp: [24, 24, 24]
  fea2denseAct: softplus #relu
  app_view_pe: 2
  app_fea_pe: 2

  TV_weight_density: 0.0005
  TV_weight_app: 0.0005


data:
  datadir: "./Neural_3D_Video/cook_spinach"
  dataset_name: neural3D_NDC
  scene_bbox_min: [-2.5, -2.0, -1.0]
  scene_bbox_max: [2.5, 2.0, 1.0]
  N_vis: 5

  datasampler_type: images
  stage_1_iteration: 300
  stage_2_iteration: 2500
  stage_3_iteration: 9000
  key_f_num: 30
  downsample: 2.0

optim:
  n_iters: 400000

render_test: True
render_path: True
expname: nv3d
