systems:
  basedir: "./logs"

model:
  model_name: "Cplane"
  N_voxel_init: 524288
  time_grid_init: 4
  time_grid_final: 8
  upsampling_type: unaligned
  upsample_list: [3000, 6000, 9000]
  update_emptymask_list: [4000, 8000, 10000]
  fusion_one: "multiply"
  fusion_two: "multiply"
  init_scale: 0.9
  init_shift: 0.5
  density_dim: 8
  DensityMode: "general_MLP"


data:
  datadir: "./Datasets_3D/MonoNeRf/data/Balloon2"
  scene_bbox_min:  [-1.5, -1.67, -1.0] 
  scene_bbox_max: [1.5, 1.67, 1.0]
  downsample: 2.0

optim:
  n_iters: 25000
  lr_decay_type: "exp"

render_test: True
render_path: True
expname: dyscene